version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

  configservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: configservice
    depends_on:
      - redis
    env_file:
      - .env.production.local
    volumes:
      - .:/app
    ports:
      - "${CONFIG_SERVICE_PORT}:${CONFIG_SERVICE_PORT}"

volumes:
  redis_data:
    driver: local
